// List of all the functions for the Shopping Cart 
// export const TYPES = {
//    ADD_TO_CART: 'TYPES.ADD_TO_CART',
//    REMOVE_ONE_FROM_CART: 'TYPES.REMOVE_FROM_CART',
//    REMOVE_ALL_FROM_CART: 'TYPES.REMOVE_ALL_FROM_CART',
//    CLEAR_CART: 'TYPES.CLEAR_CART',
// }
export const TYPES = {
   ADD_TO_CART: 'ADD_TO_CART',
   REMOVE_ONE_FROM_CART: 'REMOVE_FROM_CART',
   REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
   CLEAR_CART: 'CLEAR_CART',
}